### ISSUE TITLE
Exception when starting the server via Java Webstart

### ISSUE THREAD

**Issue by acetous** [l0rdn1kk0n/wicket-webjars#35] opened 2015-08-12 15:03 UTC
Hi!

We're starting a local server via Java Webstart. When using wicket-webjars, this exception occurs on application startup:
```
java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(Unknown Source)
	at de.agilecoders.wicket.webjars.collectors.JarAssetPathCollector.newJarFile(JarAssetPathCollector.java:56)
	at de.agilecoders.wicket.webjars.collectors.JarAssetPathCollector.collect(JarAssetPathCollector.java:37)
	at de.agilecoders.wicket.webjars.collectors.AssetsMap.getAssetPaths(AssetsMap.java:137)
	at de.agilecoders.wicket.webjars.collectors.AssetsMap.createFullPathIndex(AssetsMap.java:156)
	at de.agilecoders.wicket.webjars.collectors.AssetsMap.<init>(AssetsMap.java:46)
	at de.agilecoders.wicket.webjars.util.WebJarAssetLocator.<init>(WebJarAssetLocator.java:28)
	at de.agilecoders.wicket.webjars.util.file.WebjarsResourceFinder.newFullPathProvider(WebjarsResourceFinder.java:46)
	at de.agilecoders.wicket.webjars.util.file.WebjarsResourceFinder.<init>(WebjarsResourceFinder.java:34)
	at de.agilecoders.wicket.webjars.WicketWebjars.install(WicketWebjars.java:75)
	at de.agilecoders.wicket.webjars.WicketWebjars.install(WicketWebjars.java:51)
	at de.agilecoders.wicket.core.Bootstrap.install(Bootstrap.java:88)
	at de.agilecoders.wicket.core.Bootstrap.install(Bootstrap.java:110)
	at local.client.localClientApplication.init(localClientApplication.java:40)
	at org.apache.wicket.Application.initApplication(Application.java:823)
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:424)
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:351)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4574)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5193)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

The `path` for `new File()` in `JarAssetPathCollector.newJarFile()` is
`jar:http://devserver.local:8080/webstart/app/lib/modernizr.jar`. Java Webstart handles the local cached JAR files in a special way, so wicket-webjars does not get the correct path.

We are using wicket-webjars 0.4.4.

**Comment by martin-g** [comment] 2015-08-12 16:22
Please provide a simple quickstart application and steps to reproduce.
I have no experience with Webstart apps.

**Comment by acetous** [comment] 2015-08-14 07:51
Sadly I can not provide a sime quickstart. You would need to run a webserver and start the local server via Java Webstart which runs the quickstart app. But I can provide our bugfix.

We had to add a custom `AssetPathCollector` to load the JAR files in a webstart environment via `com.sun.jnlp.JNLPClassLoader`.
So I replaced the `JarAssetPathCollector` with these classes (the same code runs on a webserver and local via Java Webstart).

```Java
class WebstartJarAssetPathCollector extends JarAssetPathCollector {

	@Override
	public boolean accept(URL url) {
		if (super.accept(url)) {
			final String path = url.getPath();
			return path.startsWith("http:") || path.startsWith("https:");
		}
		return false;
	}

	@Override
	protected JarFile newJarFile(final URL url) {
		try {
			String path = url.getPath();
			URL jarFileLocation = new URL(path.substring(0, path.indexOf("!")));
			return JNLPClassLoader.getInstance().getJarFile(jarFileLocation);
		} catch (IOException e) {
			throw new WebJarAssetLocator.ResourceException(url.toString(), e.getMessage());
		}
	}
}
```

```Java
class LocalJarAssetPathCollector extends JarAssetPathCollector {

	@Override
	public boolean accept(URL url) {
		if (super.accept(url)) {
			final String path = url.getPath();
			return path.startsWith("file:");
		}
		return false;
	}
}
```

The `com.sun.jnlp.JNLPClassLoader` is only available in webstart environments, which include the `$JAVA_HOME/lib/javaws.jar`. So this is not a bugfix but an extension if you run wicket in a server started via webstart. Maybe you can extend the `JarAssetPathCollector` to check the protocol of the JAR-path to be `file:`.
May I add this doc for future reference to the wiki?

**Comment by martin-g** [comment] 2015-08-16 17:39
Thanks for your code snippets!
Do you want to send a Pull Request with the suggested improvements?
Since I won't be able to test the fix/improvement I think I am not in position to actually implement it. So please send a PR and if it doesn't break the normal usage then I'll apply it! 
Thanks!

**Comment by martin-g** [comment] 2016-02-25 21:11
Closing the issue.
Please send a Pull Request if you want to contribute your solution.
Thank you!

**Closed by martin-g** 2016-02-25 21:11 UTC
